-- PromptVeo3 Seed Data
-- Run this after the schema.sql to populate sample data

-- Create a system user for seeded prompts (optional)
-- You can replace this with your own user ID after registration

-- Insert sample prompts (these match the dummy data in the app)
INSERT INTO public.prompts (
  id,
  title,
  description,
  style,
  camera,
  lighting,
  environment,
  elements,
  motion,
  ending,
  text,
  keywords,
  category,
  created_by,
  is_featured,
  is_public,
  likes_count,
  usage_count,
  created_at
) VALUES 
(
  '550e8400-e29b-41d4-a716-446655440001',
  'Golden Hour Beach Rave',
  'A vibrant beach party scene during golden hour with people dancing on the sand, colorful lights, and crashing waves',
  'cinematic, vibrant, energetic',
  'wide shot, slow zoom in, handheld movement',
  'golden hour, warm sunset lighting, colorful party lights',
  'tropical beach, white sand, palm trees in background',
  ARRAY['dancing crowd', 'DJ booth', 'colorful LED lights', 'bonfire', 'waves'],
  'people dancing energetically, waves crashing, lights pulsing',
  'camera pulls back to reveal the full beach party from above',
  'none',
  ARRAY['beach', 'party', 'golden hour', 'dancing', 'tropical', 'energetic'],
  'lifestyle',
  NULL, -- Will be set to actual user after registration
  true,
  true,
  247,
  89,
  '2024-01-15T10:00:00Z'
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  'Cyberpunk City Rain',
  'A moody cyberpunk cityscape at night with neon reflections on wet streets and a lone figure walking',
  'cyberpunk, noir, atmospheric',
  'tracking shot following character, low angle',
  'neon signs, blue and pink lighting, dramatic shadows',
  'futuristic city, rain-soaked streets, tall buildings with neon signs',
  ARRAY['lone figure in coat', 'flying cars', 'holographic advertisements', 'steam from manholes'],
  'steady walking pace, rain falling, neon signs flickering',
  'character stops and looks up at massive holographic display',
  'none',
  ARRAY['cyberpunk', 'rain', 'neon', 'city', 'futuristic', 'atmospheric'],
  'sci-fi',
  NULL,
  true,
  true,
  189,
  67,
  '2024-01-14T15:30:00Z'
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'Mountain Summit Sunrise',
  'A breathtaking timelapse of sunrise from a mountain peak with clouds rolling below',
  'epic, majestic, inspirational',
  'static wide shot, slight tilt up',
  'sunrise, warm orange and pink sky, dramatic cloud lighting',
  'mountain peak, clouds below, distant mountain ranges',
  ARRAY['lone hiker silhouette', 'prayer flags', 'rocky terrain', 'rolling clouds'],
  'timelapse sunrise, clouds moving slowly, gentle flag movement',
  'full sunrise reveals vast mountain landscape',
  'none',
  ARRAY['mountain', 'sunrise', 'timelapse', 'epic', 'landscape', 'inspirational'],
  'nature',
  NULL,
  false,
  true,
  312,
  124,
  '2024-01-13T08:15:00Z'
),
(
  '550e8400-e29b-41d4-a716-446655440004',
  'Art Gallery Opening',
  'An elegant art gallery opening with sophisticated guests admiring contemporary paintings',
  'sophisticated, elegant, contemporary',
  'smooth dolly shot through gallery, medium shots of guests',
  'gallery lighting, warm spotlights on art, soft ambient lighting',
  'modern art gallery, white walls, polished floors',
  ARRAY['well-dressed guests', 'large paintings', 'wine glasses', 'gallery curator'],
  'guests moving slowly, examining art, gentle conversations',
  'focus on main artwork as crowd gathers around it',
  'none',
  ARRAY['art', 'gallery', 'sophisticated', 'contemporary', 'culture', 'elegant'],
  'lifestyle',
  NULL,
  false,
  true,
  156,
  43,
  '2024-01-12T19:45:00Z'
),
(
  '550e8400-e29b-41d4-a716-446655440005',
  'Underwater Coral Garden',
  'A mesmerizing underwater scene with colorful coral reefs and tropical fish swimming',
  'serene, colorful, mystical',
  'floating camera movement, gentle sway',
  'filtered sunlight from above, blue-green underwater ambiance',
  'coral reef, clear blue water, sandy bottom',
  ARRAY['tropical fish schools', 'colorful corals', 'sea turtle', 'floating particles'],
  'fish swimming in schools, gentle water movement, turtle gliding',
  'camera follows turtle as it swims toward surface light',
  'none',
  ARRAY['underwater', 'coral', 'marine life', 'tropical', 'serene', 'colorful'],
  'nature',
  NULL,
  true,
  true,
  278,
  91,
  '2024-01-11T14:20:00Z'
),
(
  '550e8400-e29b-41d4-a716-446655440006',
  'Space Station Interior',
  'A high-tech space station interior with astronauts working in zero gravity',
  'sci-fi, clean, futuristic',
  'floating camera movement mimicking zero gravity',
  'cool blue LED lighting, Earth light through windows',
  'space station interior, windows showing Earth, high-tech equipment',
  ARRAY['astronauts in spacesuits', 'floating objects', 'control panels', 'Earth view'],
  'astronauts floating gracefully, objects drifting, Earth rotating',
  'camera moves to window revealing full Earth view',
  'none',
  ARRAY['space', 'station', 'astronaut', 'zero gravity', 'sci-fi', 'futuristic'],
  'sci-fi',
  NULL,
  false,
  true,
  203,
  76,
  '2024-01-10T11:00:00Z'
);

-- Note: After you create your first user account, you can update the created_by field:
-- UPDATE public.prompts SET created_by = 'your-user-uuid-here' WHERE created_by IS NULL; 